### ISSUE TITLE
build: osx link failed

### ISSUE THREAD

**Issue by detailyang** [myfreeweb/go-base64-simd#2]
Undefined symbols for architecture x86_64:
  "_base64_decode", referenced from:
      __cgo_b1fab2eafdb5_Cfunc_base64_decode in _x002.o
     (maybe you meant: __cgo_b1fab2eafdb5_Cfunc_base64_decode)
  "_base64_encode", referenced from:
      __cgo_b1fab2eafdb5_Cfunc_base64_encode in _x002.o
     (maybe you meant: __cgo_b1fab2eafdb5_Cfunc_base64_encode)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by valpackett** [comment]
Is `.syso` linking supported on macos at all?
